### ISSUE TITLE
Gap between given answers and expected answers

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2339] opened 2017-05-03 10:03 UTC
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Even if my answers are correct, the expected answers are not the right ones in http://ceb.claroline.com/resource/open/ujm_exercise/15 .

![capture du 2017-05-03 11-57-29](https://cloud.githubusercontent.com/assets/14308826/25656246/64778092-2ff8-11e7-8702-298041f43b73.png)
![capture du 2017-05-03 11-57-42](https://cloud.githubusercontent.com/assets/14308826/25656249/664c2512-2ff8-11e7-85dc-8fd94889ea26.png)

**Comment by LaurentGruber** [comment] 2017-05-04 06:25
duplicate of : https://github.com/claroline/Distribution/issues/2237

**Closed by LaurentGruber** 2017-05-04 06:25 UTC
Labels: bug, ExoBundle
