### ISSUE TITLE
Conditions : Some steps are locked even without condition

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#89] opened 2016-04-07 15:14 UTC
_From @purplefish32 on March 30, 2016 9:27_

_From @Elorfin on March 16, 2016 13:22_

There are some steps that are not accessible from the Player even if the Step is not locked by a condition.

_Copied from original issue: InnovaLangues/PathBundle#309_

_Copied from original issue: claroline/ClaroSupport#7_

**Comment by LaurentGruber** [comment] 2016-04-22 07:33
J'ai également l'impression qu'il n'enregistre plus les fait, à faire, ...

**Comment by purplefish32** [comment] 2016-05-25 08:22
@Elorfin : On en est ou de ce ticket ?

**Comment by Elorfin** [comment] 2016-05-25 08:23
Il me semble qu'Olivier a fait une PR qui devrait régler le problème, mais j'ai pas encore pris le temps de tester.

**Comment by purplefish32** [comment] 2016-05-25 08:41
@CPASimUSante : Tu peut nous éclairer ?

**Comment by CPASimUSante** [comment] 2016-05-25 09:13
laurent reported that on a new instance of Claro with my PR merged, he had th same pb. he sent me a screenshot. He gave me a login/pwd to test the same Path. I tried it on Windows 7 : IE11, Chrome, FF and on Debian 8  Iceweasel => no pb for me... I can't reproduce it. As suggested Nico : maybe a browser cache pb ?

Form Laurent
![laurent](https://cloud.githubusercontent.com/assets/14015697/15534441/1c99ac66-2269-11e6-9e80-b8bcc54d4a07.png)

From me : 
Firefox

![parcours-ff](https://cloud.githubusercontent.com/assets/14015697/15534575/b1b958dc-2269-11e6-8b8f-4e16f95d14cb.jpg)

Chrome
![parcours-chrome](https://cloud.githubusercontent.com/assets/14015697/15534553/97bc6186-2269-11e6-80fe-7fb1e8889638.jpg)

IE11

![parcours-ie](https://cloud.githubusercontent.com/assets/14015697/15534534/891f84e6-2269-11e6-9fc6-00095cb90999.jpg)

Iceweasel

![parcours-iceweasel](https://cloud.githubusercontent.com/assets/14015697/15534503/6ae958bc-2269-11e6-8de7-3812a13c7730.jpg)

**Comment by eddymarques** [comment] 2016-05-25 09:38
With the very last update, this problem has disappeared on our dev server

**Comment by CPASimUSante** [comment] 2016-05-25 09:40
ok, must be confirmed too on laurent's side.

What worries me is, even with the previous path version, i didn't have this bug :(

**Comment by Elorfin** [comment] 2016-05-25 09:54
@CPASimUSante : IMHO it can be because : 
- You have already seen all the steps of the Path in your test data. So the UserProgression is correctly populated.
- You use an administrator : maybe the problem is only when you are User ?

**Comment by CPASimUSante** [comment] 2016-05-25 10:06
@Elorfin 

- i hadn't seen them all : i tested them and did the scrennshot afterwards (ex: my Chrom screenshot). And as you can see for Module 3 (screenshot IE11) i only clicked on 1 step.
- That's what i asked Laurent : it seems i am at least manager. I would like to test it as a regular Collaborator. 

But, in fact, it should act the same way as a user than the manager : in my tests, i created a condition for people belonging to a team. the manager wasn't part of it => he had the blocking message

**Comment by LaurentGruber** [comment] 2016-05-26 10:33
ça à l'air bon chez moi également :)

**Closed by LaurentGruber** 2016-05-26 10:33 UTC
Labels: bug, PathBundle
