### ISSUE TITLE
[ExoBundle] Helpful enhancements

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2150] opened 2017-03-21 08:01 UTC
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

I'm listing here a few enhancements that some of our users proposed and we found them really useful.

- [x] Allow question duplicate. Add an option to duplicate a question since for many cases the question description may be practically the same for multiple questions.

- [ ] Add "Save" button in the bottom of the quizz as well. Let's imagine the case when someone creates a quizz with let's say more than 25 questions. When he wants to save the quizz he is constantly forced to scroll to the top, save and the scroll down to where he was to continue his work. It's not very "handy".

**Comment by Elorfin** [comment] 2017-03-24 09:57
First point is a duplicate of #1626.

**Closed** 2019-03-26 14:56 UTC
Labels: Ergonomie, ExoBundle, enhancement
